export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FILE_ADDITION = "FILE_ADDITION";
export const START_UPLOADING = "START_UPLOADING";
export const FILE_PROGRESS_REPORT = "FILE_PROGRESS_REPORT";
export const FINISH_UPLOADING = "FINISH_UPLOADING";
export const CLEAR_UPLOADED_FILES = "CLEAR_UPLOADED_FILES";
